게시글 조회 기능 추가하였습니다.
No-Break/personal-posts pull request #25
Opened 2021-07-02 13:10 UTC by OseongminO

스프링 시큐리티 설정때문에 내용을 지웠는데도 오류가 계속 발생하여
PR후 프로젝트 다시 받아서 확인이 필요할것같습니다...

2021-07-03 00:01 UTC, abcshc requested changes
수고하셨습니다. 🥳
실제 많은 API를 만들면서 `RESTful` 에 대한 이해를 높이면 좋겠습니다.

2021-07-03 00:01 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/SmBoardController.kt
> +    @PostMapping("/addBoard")
기존 `/boards`가 더 좋아보입니다. url에서는 동작보다는 resource를 나타내는 것이 좋아 보입니다.
원호 PR https://github.com/No-Break/personal-posts/pull/22 에서 리뷰 내용도 참고해주세요

2021-07-03 00:01 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/SmBoardController.kt
> +    fun getPost(): ResponseEntity<Any> {
위 addBoard url에서는 `/boards`로 리소스만 표현하고 HTTP 메소드를 GET으로 사용하는게 `RESTful`에 적합한 것 같습니다.

이렇게 REST API endpoint를 표준에 맞추는 이유는 미리 정해진 약속으로 서버, 클라이언트 간의 협업에 생산성을 높이기 위함입니다.
일이 아닌 스터디인 만큼 표준에 따라 다른 많은 개발자들이 공감할 수 있는 인터페이스를 맞춰보도록 합시다.

그리고 ResponseEntity의 타입을 Any보다는 구체적으로 스펙을 정하는 것이 좋아보입니다.
다른 개발자가 API를 확인할 때의 편의와 `swagger`나 `Spring REST Docs`가 문서를 생성하기 위해서는 Response를 위한 객체가 필요로 합니다.

2021-07-03 00:01 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/repository/BoardRepository.kt
>  }
Nit: 이전 원호 PR 리뷰에서도 이야기 했었던 No newline at end of file을 없애기 위해 intellij 옵션을 설정 부탁드립니다. https://github.com/No-Break/personal-posts/pull/22#discussion_r655734337

2021-07-03 00:01 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/SmBoardController.kt
> +    fun getUserPost(@RequestParam userId: String): ResponseEntity<Any> {
위 항목들과 같이 `RESTful`에 맞추면 좋겠습니다. `/boards` 의 `@RequestParam` 의 조건으로 합쳐지거나 
`GET /users/{userId}/boards` 형태로도 가능할 것 같습니다.

기존 prefix를 유지하려면 `/boards/users/{userId}`도 괜찮을거 같은데 실제 사용자 입장에서 어디서 활용되는지에 따라 선택하면 될 것 같습니다.

2021-07-09 13:10 UTC, OseongminO commented on src/main/kotlin/study/nobreak/personalposts/sm/repository/BoardRepository.kt
>  }
확인후 설정 변경하였습니다.

2021-07-09 22:49 UTC, abcshc approved these changes
수고하셨습니다 👍

2021-07-10 01:27 UTC, choiwonho approved these changes

2021-07-10 01:27 UTC, choiwonho commented on src/main/kotlin/study/nobreak/personalposts/sm/service/SmBoardService.kt
> +}
getPost() 와 getUserPost() 메서드의 역할이 실제 구현될때 무슨 역할을 하는지 알 수 있는것 같습니다.
인터페이스에서도 메서드 네이밍만 보고 무슨 역할인지 유추하기 쉬우면 더 좋을 것 같습니다!

2021-07-10 01:27 UTC, merged