Feature/user
No-Break/personal-posts pull request #3
Opened 2021-03-24 12:38 UTC by OseongminO

코틀린 처음써봄

2021-03-24 12:39 UTC, abcshc approved these changes, later dismissed

2021-03-24 12:39 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/smController.kt
> +    fun hello(): String = "hello world"
잘했습니다.

2021-03-26 01:36 UTC, choiwonho approved these changes, later dismissed
@GetMapping 작업이 추가 될 예정인가요?

2021-03-26 23:40 UTC, abcshc requested changes
열심히 하는 모습 보기 좋습니다. 👍

2021-03-26 23:40 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/smController.kt
> +class smController {
클래스 는 맨 앞은 대문자로 부탁드립니다.
https://kotlinlang.org/docs/coding-conventions.html#naming-rules
저희는 코틀린이 정해준 네이밍 규칙을 따르려고 합니다.

2021-03-26 23:40 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/smController.kt
> +    fun index(model: Model):String{
각 변수명, 타입에 대한 띄워쓰기는 `변수명: 타입` 으로 해주세요.
우선 intellij의 기본 코드 스타일을 따라갈 예정입니다. 
(추후 다른 IDE에서도 같은 포멧을 사용할 수 있도록 하겠습니다.)
커밋 전에 ⌥⌘L 또는 Ctrl+Alt+L 를 통해 Reformat Code를 사용해주세요.

2021-03-26 23:40 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/smController.kt
> +        return "find"
`@RestController`는 `@ResponseBody`가 포함된 컨트롤러이기 때문에 mustache로 html template를 사용할 수 없습니다.
`@Controller`로 바꾸어 주고 객체를 반환하는 부분을 `@ResponseBody`를 붙여주거나 별도의 컨트롤러 클래스를 새로 만들어야할 것 같습니다.
그리고 html template은 맵핑될 html 파일이 있어야 하는데 현재 없는 것 같습니다.

2021-03-26 23:40 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/smController.kt
> +    lateinit var repository:UserRepository
필드를 통해 주입하면 순환 참조 방지를 할 수 없습니다. 생성자 주입으로 바꾸는 게 어떨까요?

2021-03-26 23:40 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/smUser.kt
> +class smUser(
`smController`와 마찬가지로 맨 앞자리는 대문자로 해주세요

2021-03-26 23:40 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/smController.kt
> +        try{
일괄적인 예외 처리를 하는 이유가 무엇인가요?

2021-03-26 23:42 UTC, abcshc commented
> @GetMapping 작업이 추가 될 예정인가요?

@choiwonho  리뷰로 코드에 코멘트 남겨주세요

2021-03-28 13:11 UTC, OseongminO reviewed
> @GetMapping 작업이 추가 될 예정인가요?

@choiwonho 좀더 자세히 설명부탁드립니다.

2021-03-28 13:11 UTC, OseongminO commented on src/main/kotlin/study/nobreak/personalposts/sm/smController.kt
> +    fun hello(): String = "hello world"
감사합니다.

2021-03-28 13:11 UTC, OseongminO commented on src/main/kotlin/study/nobreak/personalposts/sm/smController.kt
> +class smController {
네 그렇게 수정하겠습니다.

2021-03-29 00:48 UTC, abcshc approved these changes
👍

2021-03-29 01:16 UTC, merged