Feature/user
No-Break/personal-posts pull request #4
Opened 2021-04-03 11:14 UTC by OseongminO

컨트롤러와 서비스로 분리해보았습니다.

2021-04-04 04:53 UTC, abcshc requested changes
고생하셨습니다. 추가적인 학습이 필요해 보이는 부분과 논의가 필요한 부분들을 코멘트로 남겼습니다. 조만간 전체 만남 일정을 조율하여 이야기 해보아요!

2021-04-04 04:53 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/SmController.kt
> +    @GetMapping("/sign")
사용자를 등록하는 것은 Post Method를 사용하는 것이 좋아 보입니다.
REST API 설계 방법에 대해서 학습했으면 좋겠습니다.

2021-04-04 04:53 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/SmController.kt
> +        println("result: $user")
디버깅을 위해 만든 코드는 커밋 전에 삭제해 주세요.

2021-04-04 04:53 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/SmController.kt
> +        //return ""
결과 응답에 대한 body는 리턴하지 않더라도 response code를 201 로 설정했으면 좋겠습니다.
위와 같이 REST API method, response code에 대해서 학습을 하면 좋겠습니다.

2021-04-04 04:53 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/SmController.kt
> +        smUserService.checkSmUser(model,session,userId,password)
지난 PR에 말씀드린 띄어쓰기 규칙대로 되어있지 않은 것 같습니다.
Intellij의 plugins에 Save Action을 사용하여 저장 시 자동으로 포멧을 맞추는 것도 좋을 것 같습니다.

2021-04-04 04:53 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/SmUserServiceImpl.kt
> +    override fun checkSmUser(model: Model, session: HttpSession, userId:String, password:String):String{
저희가 Service, Controller 계층 간의 역할을 먼저 정의하지는 않았지만 loose coupling을로 의존성을 줄여 재사용성을 높이는 것이 좋은 것 같습니다.
세션 모델을 가져와서 변경하지 않고 User를 반환하여 컨트롤러에서 세션과 모델을 설정하는 것이 좋은 것 같습니다.
그렇게 되면 checkSmUser가 아닌 다른 이름의 User정보를 조회하는 서비스가 될 것입니다.

다음 전체 만남 때 Controller와 Service의 정의에 대해서 논의했으면 좋겠습니다.

2021-04-08 11:22 UTC, starr9622 commented on src/main/kotlin/study/nobreak/personalposts/sm/Repositories.kt
> +}
마지막 라인에 공백 라인 추가해주세용 :)

2021-04-12 11:15 UTC, abcshc submitted a review, later dismissed
수고하셨습니다. conflict 해결 부탁드립니다.

2021-04-13 00:24 UTC, OseongminO commented
@abcshc conflict 확인 하였습니다.
@choiwonho pending reviewer 확인 부탁드리겠습니다.

2021-04-13 04:42 UTC, abcshc approved these changes

2021-04-13 04:45 UTC, merged