Create get data
No-Break/personal-posts pull request #5
Opened 2021-04-11 08:17 UTC by choiwonho

Get data from table name contents using for posts API data

2021-04-12 14:18 UTC, abcshc requested changes
동작하지 않은 코드들이 보입니다.
그외에는 응답 VO를 별도로 만들거나 테이블, 엔티티를 단수, 복수에 대한 선택은 취향이 될 수 있으므로 각자의 게시판을 개발하고 있기 때문에 따로 코멘트는 남기지 않았습니다. 나중에 함께 개발할 때 논의하고 진행하면 좋을 부분으로 보입니다.

2021-04-12 14:18 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/wonos/contents/domain/Contents.kt
> +    var title: String = "",
프로퍼티 끝에는 `,`가 들어갈 수 없을 것 같습니다.  생성자에 들어가거나 프로퍼티로 들어갈 경우 `,`를 빼주세요.

2021-04-12 14:18 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/wonos/contents/ContentsController.kt
> +    fun getPosts(): ResponseEntity<*> {
ResponseEntity가 import되어 있지 않습니다. 확인 부탁드립니다.

2021-04-13 04:54 UTC, OseongminO commented on src/main/kotlin/study/nobreak/personalposts/wonos/contents/domain/Contents.kt
> +    var title: String = "",
data class를 사용한 이유가 있나요?

2021-04-19 08:36 UTC, OseongminO submitted a review, later dismissed

2021-04-20 23:09 UTC, abcshc requested changes

2021-04-20 23:09 UTC, abcshc commented on .gitignore
> +.yml
yml 파일 전체를 ignore하게 되면 설정파일 적용되기 어려울 것 같습니다. 
현재 PR 중인 Travis CI 추가에도 `.yml` 이 포함되어 있습니다.
구체적인 파일 이름, 경로를 설정해주세요.

2021-04-20 23:09 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/wonos/contents/domain/Contents.kt
> +//import javax.validation.constraints.NotBlank
사용하지 않는 경우 주석말고 삭제 해주세요

2021-04-20 23:09 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/wonos/contents/ContentsController.kt
> +    private val contentsServiceImpl: ContentsServiceImpl
서비스의 빈 주입을 효과적으로 이용하려면 구현체를 주입하는 것이 아닌 인터페이스를 주입해야합니다. 
인터페이스만 사용하여도 구현체(`ContentsServiceImpl`)가 하나이기 때문에 특별한 설정 없이 주입이 가능합니다.
만약 구현체가 2개 이상일 경우 `@Qualifier` 를 사용하여 이름을 지정하여 주면 됩니다.

2021-04-21 00:13 UTC, choiwonho commented on .gitignore
> +.yml
네 수정해놓겠습니다.

2021-04-21 11:57 UTC, abcshc approved these changes

2021-04-21 11:57 UTC, merged