Feature/board
No-Break/personal-posts pull request #7
Opened 2021-04-16 04:52 UTC by OseongminO

게시글 작성부분 구현했습니다.

추가적으로 필요할수 있는 부분 좀더 고민하여
추가 하도록 하겠습니다.

2021-04-16 12:27 UTC, abcshc requested changes
고생하셨습니다. 커밋 목록이 이전 것들이 다 올라온 것으로 보아 main에서 checkout에 문제가 있었던 것 같습니다. git rebase를 잘 활용할 수 있으면 좋겠습니다.

2021-04-16 12:27 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/SmBoardController.kt
> +    @PostMapping("/boardSave")
REST API 에서 post는 리소스를 생성한다는 의미를 가지고 있습니다. save는 빼는 것이 좋은 것 같습니다.

2021-04-16 12:27 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/SmBoardController.kt
> +    fun boardSave(smBoard: SmBoard): ResponseEntity<Any> {
일반적으로 함수 이름은 동사 + 목적어의 구조를 가집니다. 정해진 규칙은 아니지만 함수를 통해 동작하는 바를 명확히 전달하는 방법을 고민하고 논의했으면 좋겠습니다.

2021-04-16 12:27 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/SmBoardServiceImpl.kt
> +        return board
Nit: return boardRepositories.save(smBoard) 로 한줄로 하더라도 가독성이 떨어지지 않을 것 같고 라인이 줄 수 있을것 같습니다.

2021-04-16 12:27 UTC, abcshc commented on src/main/kotlin/study/nobreak/personalposts/sm/UserRepositories.kt
> +interface UserRepositories : CrudRepository<SmUser, Long> {
해당 인터페이스는 User와 관련된 저장소로 복수인 Repositories 보다 단수인 Repository가 더 적합해보입니다.

2021-04-19 08:16 UTC, choiwonho approved these changes
확인했습니다!

2021-04-19 08:38 UTC, abcshc approved these changes
👍

2021-04-19 08:42 UTC, merged